# Generated by Django 5.0 on 2023-12-28 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, help_text='Unique User ID.', primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Enter a unique Username.', max_length=25, unique=True)),
                ('email', models.EmailField(help_text='Enter a unique Email.', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Enter a Password.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MC_Game',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, help_text='Unique Game ID.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a name for your Game.', max_length=100, unique=True)),
                ('youtube_video_url', models.URLField(help_text='Enter the Youtube Video URL for the Game.')),
                ('youtube_video_id', models.CharField(help_text='Enter the Youtube Video Id for the Game', max_length=100)),
                ('date_created', models.DateField(help_text='Enter the date of Game creation.')),
                ('num_plays', models.IntegerField(help_text='Enter the number of times this Game has been played.')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='frequenplay.user')),
            ],
        ),
    ]
