# Generated by Django 5.0 on 2024-01-03 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceGame',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid1, help_text='Unique Game ID.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a name for the Game.', max_length=100, unique=True)),
                ('youtube_video_url', models.URLField(help_text='Enter the Youtube Video URL for the Game.')),
                ('youtube_video_id', models.CharField(help_text='Enter the Youtube Video Id for the Game', max_length=100)),
                ('pub_date', models.DateField(help_text='Enter the date of Game creation.')),
                ('num_plays', models.IntegerField(default=0, help_text='The number of times this Game has been played.')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
