# Generated by Django 5.0 on 2024-01-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequenplay', '0002_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='game_id',
            new_name='game',
        ),
    ]
