name: YouTube Operational API
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: git clone --depth 1 https://github.com/Benjamin-Loison/YouTube-operational-API
      # Unclear how to get rid of `2> /dev/null`, as `SERVER_NAME='localhost'` involves an issue in `REQUEST_URI='/channels.php' HTTP_HOST='localhost' SERVER_NAME='localhost' php-cgi -f YouTube-operational-API/channels.php handle=@WHO`
      - run: php-cgi -f YouTube-operational-API/channels.php handle=@WHO 2> /dev/null